strategy:
  matrix:
    windows:
      imageName: 'windows-2022'
    mac:
      imageName: 'macOS-11'
    linux:
      imageName: 'ubuntu-22.04'

trigger:
- none

pool:
  vmImage: $(imageName)

steps: 
  - task: GoTool@0
    inputs:
      version: '1.22.1'
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    inputs:
      command: 'build'
      arguments: '-ldflags "-s -w"'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    inputs:
      Contents: '**/Simserver'
      TargetFolder: '$(System.DefaultWorkingDirectory)/$(imageName)/'
  - task: CopyFiles@2
    inputs:
      Contents: '**/Simserver.exe'
      TargetFolder: '$(System.DefaultWorkingDirectory)/$(imageName)/'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(imageName)'
      includeRootFolder: true
      archiveType: '7z'
      sevenZipCompression: 'ultra'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(imageName)/$(imageName)_$(Build.BuildId).7z'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop